### ISSUE TITLE
Pip install fails

### ISSUE THREAD

**Issue by hunterowens** [jackmaney/k-means-plus-plus-pandas#3]
hunter-owenss-macbook-pro-7:_posts howens$ sudo pip install k-means-plus-plus
Downloading/unpacking k-means-plus-plus
  Downloading k-means-plus-plus-0.0.6.tar.gz
  Running setup.py (path:/private/tmp/pip_build_root/k-means-plus-plus/setup.py) egg_info for package k-means-plus-plus
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/tmp/pip_build_root/k-means-plus-plus/setup.py", line 3, in <module>
        import k_means_plus_plus as kmpp
    ImportError: No module named k_means_plus_plus
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/tmp/pip_build_root/k-means-plus-plus/setup.py", line 3, in <module>

    import k_means_plus_plus as kmpp

ImportError: No module named k_means_plus_plus

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/k-means-plus-plus
Storing debug log for failure in /Users/howens/Library/Logs/pip.log

**Comment by jackmaney** [comment]
My apologies for taking so long to fix this. Life has it's way of getting in the way...

Anyways, 0.1.0 is now up. Also, this implementation of k-means++ is a lot slower than [that of scikit-learn](http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html), so you should use that in production instead.
